---
sudo: false
language: php
dist: trusty

matrix:
  include:
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
      env:
        - RUN_LINTER=1
        - RUN_SNYK=1
    - php: 'master'
    - php: 'nightly'
  fast_finish: true
  allow_failures:
    - php: 'master'
    - php: 'nightly'

before_install:
  - composer install -n --prefer-source
  - phpenv rehash
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then sudo apt-get install -y nodejs; npm install -g snyk; fi"

install:
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then snyk test --org=maxmind; fi"

script:
  - mkdir -p build/logs
  - "if [[ $RUN_LINTER ]]; then vendor/bin/php-cs-fixer fix --verbose --diff --dry-run --config=.php_cs; fi"
  - "if [[ $RUN_LINTER ]]; then vendor/bin/phpcs --standard=PSR2 src/; fi"
  - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls

after_success:
  - "if [[ $RUN_SNYK && $SNYK_TOKEN && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then snyk monitor --org=maxmind --project-name=maxmind/GeoIP2-php; fi"
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "OtowN1lGa5MAhn6gl87aB3kXXeOKLGIb4e9dBud/tPt/1sQDoZVj6m6VWtpsXh6iXL7lWetVbpmeZCydSRumgVMIy7+45uMQPvdoWBFCT+rq67yDb3gyvFknpjBuit0Q91lTDoGTUSgtqk+PSZX5LvDgT4b8WQFBb/dcB35hqis=\n"
env:
  global:
    secure: "Ptt+TYu7h430sdv9WjIlKS6kWdwQQYapv8OYuZZ2sUrcynuHkMw3OMp+p3Y86KAMCd2ZwlOyeLA1V2QrifkiC9i1KmEqiH6eZcrzdt+YgrBK6S1BRjbrhabPBs6iT3ey6NxU+hEgl/+pb2R1VlKi1B5Fw7rJ1S6/34VhvgEpwDc="
